import 'package:flutter/material.dart';
import 'package:testing1212/data/my_colors.dart';

const String google_api_key = "API_KEY";
const Color primaryColor = MyColors.navBarColor;
const double padding = 16.0;
const baseUrl = 'https://teklehaimanothospital.com/api';
const loginUrl = '$baseUrl/loginapi.php';
const registerUrl = '$baseUrl/Register.php';
const sliderUrl = '$baseUrl/sliderGetData.php';
const  departmentCountUrl = '$baseUrl/departmentCountGetData.php';
const aboutUrl = '$baseUrl/aboutGetData.php';
const testimonialUrl = '$baseUrl/testimonialGetData.php';
const doctorCountUrl = '$baseUrl/doctorsCountGetData.php';
const patientUrl = '$baseUrl/patientGetData.php';
const bookingUrl = '$baseUrl/bookingAndDoctorGetData.php';
const departmentUrl = '$baseUrl/departmentGetData.php';
const scheduleByIdUrl = '$baseUrl/scheduleGetDataById.php';
const allDoctorsUrl = '$baseUrl/doctorGetData.php';
const doctorByDepartment = '$baseUrl/doctorGetDataByDepartmentId.php';
const eventUrl = '$baseUrl/eventGetData.php';
const healthTipUrl = '$baseUrl/newsGetData.php';
const addBookingUrl = '$baseUrl/Booking.php';
const serviceUrl = '$baseUrl/serviceGetData.php';
const teamsUrl = '$baseUrl/teamGetData.php';
const timeTableUrl = '$baseUrl/scheduleAndDoctorGetData.php';
const doctorsByNameUrl = '$baseUrl/doctorGetDataByName.php';
const doctorsByNameAmUrl = '$baseUrl/doctorGetDataByNameAm.php';
const userProfileUrl = '$baseUrl/userGetData.php';
const updateProfileUrl = '$baseUrl/UpdateProfile.php';
const uploadImageUrl = '$baseUrl/upload_image.php';
const error404 = '404';
const something = 'something';